version: "3.8"

services:
  db:
    image: postgres:15
    container_name: pg_transfer_example_container
    restart: always
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
